# Chapter 1 Introduction

## What kind of problems? Why first principle is difficult?

- when the application rules may change a lot according to new situations.
- when the input data and related computation are too complex to tackle with rules.


## key component of machine learning

- input data
- model(parameters)
- objective function
- optimization algorithm


## supervised learning

sample + labels

### regression
answer the question **how many?**

typical loss function: mean square loss (assuming data were corrupted by Gaussian Noise)
### classification

anser the question **which one?**

setup output in a probability approach which is easier for optimization

typical loss function: cross entropy loss

binary, multiclass, multi-label(not mutually exclusive), hierarchical classification

- tagging
- search(Pangerank)
- recommender system: problems as deal with censoring, incentives, and feedback loops
- sequence learning: Tagging and Parsing; Automatic Speech Recognition; Text to speech; Machine Translation;


## unsuperised learning

- Can we find a small number of prototypes that accurately summarize the data? Clustering.
- Can we find a small number of parameters that accurately capture the relevant properites of the data? Subspace extimation/ Principal component anaylsis
- Is there a representation of objects in Euclidean space such that symbolic properties can be well matched?
- Is there a description of the root causes of much of the data that we observe? Causality/ Probabilistic graphical models
- Generative adversial networks.

## Reinforcement learning

- we can formulate any superivsed learning problems into RL.
- RL can address many problems that supervised learning cannot. For example RL do not assume that for each observation the environment tells us the optimal action.

- need deal with the problem of credit assignment; partial observability problem; exploit vs explore

- comlexity issue is huge.

- Markov decision process: when env is fully observed
- Contextual bandit problem: state does not depend on the previous actions
- multi-armed bandit problem: no state, just a set of available actions with initially unkown rewoards.


## Example of Important progresses:

- Novel methodes for capacity control: e.g. Dropout
- Attention mechanisms
- Multi-stage designs
- GAN
- Paralelize computation
- Deep Learning Frameworks

# Chapter2 Preliminaries

In [1]:
import torch

In [2]:
x =torch.arange(12, dtype=torch.float32)

In [3]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.shape

torch.Size([12])

In [6]:
x.numel()

12

In [7]:
X=x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
x.reshape(-1,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
x.reshape(3,-1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
torch.randn(3,4)

tensor([[-0.5603, -1.2947,  1.1689, -1.4815],
        [ 0.9108, -0.0809, -0.3887, -0.8095],
        [-1.0935,  0.1845,  0.1581,  0.8024]])

In [14]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [15]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])

x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [16]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [17]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y), axis=0), torch.cat((X,Y), axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [18]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [19]:
X.sum()

tensor(66.)

broadcasting
operation between tensors with different shapes
1. expand one or both tensors by copying elements approprately, so that after this transformation, the two tensors have the same shape.
2. carry out elementwise operations on the resulting tensors.

In [20]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [22]:
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))